apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/letfn/katt-kuma/global?ref=0.0.2

patches:
  - path: patch-nodeport-global.yaml
    target:
      kind: Service
      name: kuma-global-zone-sync
  - path: patch-nodeport-control.yaml
    target:
      kind: Service
      name: kuma-control-plane
