apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mean--kuma-global
  namespace: argocd
spec:
  project: mean
  source:
    repoURL: 'https://github.com/amanibhavam/dev--mean'
    path: kuma-global
    targetRevision: 0.0.1
  destination:
    name: mean
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
